services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8001:8000"        # host 8001 -> container 8000
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8000 | grep -q DynamoDB"]
      interval: 2s
      timeout: 2s
      retries: 30

  api:
    build: .
    depends_on:
      dynamodb:
        condition: service_healthy
    environment:
      - DDB_TABLE_NAME=Reports
      - AWS_REGION=eu-central-1
      - AWS_DDB_ENDPOINT=http://dynamodb:8000
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - CORS_ORIGIN=http://localhost:5173
      - LOG_LEVEL=DEBUG
      - FAKE_ANALYZER=1
    ports:
      - "8000:8000"
    command: >
      sh -c "
      python scripts/bootstrap_dynamodb.py &&
      python -m uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --reload
      "
